export const bases= `Aviso para el consultorio tratante: este formulario debe ser firmado por sus pacientes de Wave® antes del tratamiento y guardado para sus registros.
CONSENTIMIENTO INFORMADO Y ACUERDO DEL PACIENTE EN RELACIÓN CON EL TRATAMIENTO DE ORTODONCIA WAVE®
Su médico le ha recomendado el sistema Wave® para su tratamiento de ortodoncia. Aunque el tratamiento de ortodoncia puede conducir a una sonrisa más saludable y atractiva, también debe tener en cuenta que cualquier tratamiento de ortodoncia (incluido el tratamiento de ortodoncia con alineadores Wave) tiene limitaciones y riesgos potenciales que debe considerar.
DESCRIPCION DEL DISPOSITIVO
Alineadores Wave®, desarrollados por Osteoblast SAS. ("Osteoblast") consisten en una serie de aparatos removibles de plástico transparente que mueven los dientes en pequeños movimientos. Los productos Wave® combinan el diagnóstico y la prescripción de su médico con una sofisticada tecnología de gráficos por computadora para desarrollar un plan de tratamiento que especifica los movimientos deseados de sus dientes durante el curso de su tratamiento. Tras la aprobación de un plan de tratamiento desarrollado por su médico, se produce una serie de alineadores Wave personalizados específicamente para su tratamiento.
DURACION DEL TRATAMIENTO
El precio del tratamiento de alineadores invisibles Wave abarcará las etapas planificadas inicialmente, así como un posible proceso de refinamiento adicional en caso de ser necesario para lograr los resultados deseados.
El tiempo de duración del tratamiento estará sujeto a la cantidad de alineadores planificados y a su correcto uso por parte del paciente. Es importante seguir las instrucciones proporcionadas por el profesional de salud bucodental para garantizar un progreso efectivo.
Se establece que la cantidad máxima de alineadores para un tratamiento será de 90 en total, incluyendo las etapas definidas y cualquier refinamiento requerido. Se informa al paciente que, una vez alcanzado este límite, cualquier alineador adicional no estará cubierto en el precio inicial abonado.
PROCEDIMIENTO
Es posible que se someta a un examen previo al tratamiento de ortodoncia de rutina que incluya radiografías (rayos X), fotografías y un escaneo intraoral. Además, su médico enviará un informe con la prescripción del tratamiento. Los técnicos de Wave® seguirán la prescripción de su médico para crear una propuesta de tratamiento. Tras la aprobación del plan de tratamiento por parte de su médico, Wave® producirá y enviará una serie de alineadores personalizados a su médico. El número total de alineadores variará según la complejidad de su maloclusión y el plan de tratamiento del médico. Los alineadores estarán numerados individualmente y su médico se los entregará con instrucciones específicas de uso. A menos que su médico le indique lo contrario, debe usar sus alineadores durante aproximadamente 20 a 22 horas por día, quitándoselos solo para comer, cepillarse los dientes y usar hilo dental. Según las indicaciones de su médico, cambiará al siguiente alineador de la serie cada dos o tres semanas. La duración del tratamiento varía según la complejidad de la prescripción de su médico. A menos que se le indique lo contrario, debe hacer un seguimiento con su médico cada 4 a 6 semanas como mínimo.
Algunos pacientes pueden requerir aditamentos estéticos adheridos y/o el uso de elásticos durante el tratamiento para facilitar movimientos de ortodoncia. Los pacientes pueden requerir más escaneos y/o alineadores de refinamiento después de la serie inicial de alineadores.
BENEFICIOS
•	Los alineadores Wave® ofrecen una alternativa estética a los Brackets convencionales.
•	Los alineadores son casi invisibles, por lo que muchas personas no se darán cuenta de que está en tratamiento.
•	Los planes de tratamiento se pueden visualizar a través del informe entregado a su odontólogo.
•	Los alineadores permiten las tareas normales de cepillado y uso de hilo dental que generalmente se ven afectadas por los aparatos ortopédicos convencionales.
•	Los alineadores no tienen los alambres metálicos ni los soportes asociados con los aparatos ortopédicos convencionales.
•	El uso de alineadores puede mejorar los hábitos de higiene bucal durante el tratamiento.
RIESGOS Y POSIBLES INCONVENIENCIAS
Al igual que otros tratamientos de ortodoncia, el uso de los productos Wave® puede implicar algunos de los riesgos que se describen a continuación:
(i)	No usar los aparatos durante la cantidad requerida de horas por día, no usar el producto según las indicaciones de su médico, faltar a las citas y los dientes en erupción o con formas atípicas pueden prolongar el tiempo del tratamiento y afectar la capacidad de lograr los resultados deseados;
(ii)	Se puede experimentar sensibilidad dental después de cambiar al siguiente alineador de la serie;
(iii)	Las encías, las mejillas y los labios pueden irritarse;
(iv)	Los dientes pueden cambiar de posición después del tratamiento. El uso constante de contenciones al final del tratamiento debería reducir esta tendencia;
(v)	Pueden producirse caries, enfermedad periodontal, inflamación de las encías o marcas permanentes (p. ej., descalcificación) si los pacientes consumen alimentos o bebidas que contienen azúcar, no cepillarse los dientes y usar hilo dental correctamente antes de usar los productos Wave®, o no usar una higiene oral adecuada y un mantenimiento preventivo;
(vi)	Los alineadores pueden afectar temporalmente el habla y provocar un ceceo, aunque cualquier impedimento del habla causado por los productos Wave debería desaparecer en una o dos semanas;
(vii)	Los alineadores pueden causar un aumento temporal de la salivación o sequedad de la boca y ciertos medicamentos pueden aumentar este efecto;
(viii)	Los aditamentos se pueden adherir a uno o más dientes durante el curso del tratamiento para facilitar el movimiento de los dientes y/o la retención del aparato. Estos se eliminarán una vez que se complete el tratamiento;
(ix)	Los dientes pueden requerir desgaste interproximal (IPR o Stripping) para crear el espacio necesario para que se produzca la alineación dental;
(x)	La mordida puede cambiar a lo largo del tratamiento y puede resultar en molestias temporales para el paciente;
(xi)	Después del final del tratamiento de ortodoncia, la mordida puede requerir un ajuste ("ajuste oclusal").
(xii)	Tratamiento de ortodoncia complementario, incluido el uso de botones adheridos, elásticos de ortodoncia, aparatos auxiliares/dispositivos dentales (p. ej., dispositivos de anclaje temporal, aparatos fijos) y/o procedimientos dentales restaurativos pueden ser necesarios para planes de tratamiento más complicados donde los alineadores por sí solos pueden no ser adecuados para lograr el resultado deseado.
(xiii)	Pueden generarse “triángulos negros”
(xiv)	Los implantes dentales no pueden moverse con alineadores.
(xv)	Las condiciones médicas generales y el uso de medicamentos pueden afectar el tratamiento de ortodoncia;
(xvi)	La salud de los huesos y las encías que sostienen los dientes puede verse afectada;
(xvii)	Un diente que ha sido previamente traumatizado o significativamente restaurado puede estar agravado con el tratamiento Wave®. En casos raros, la vida útil del diente puede reducirse, el diente puede requerir tratamiento dental adicional como endodoncia y/o trabajo de restauración adicional. Existe la posibilidad de que se pierda un diente.
(xviii)	Las restauraciones dentales existentes (p. ej., coronas) pueden desprenderse y requerir una nueva cementación o, en algunos casos, un reemplazo;
(xix)	Las coronas clínicas cortas pueden plantear problemas de retención de aparatos e inhibir el movimiento de los dientes;
(xx)	La longitud de las raíces de los dientes puede acortarse durante el tratamiento de ortodoncia y puede convertirse en una amenaza para la vida útil de los dientes;
(xxi)	La rotura del producto es más probable en pacientes con apiñamiento severo y/o múltiples dientes faltantes;
(xxii)	Los aparatos de ortodoncia o partes de los mismos pueden tragarse o aspirarse accidentalmente;
(xxiii)	En raras ocasiones, también pueden ocurrir problemas en la articulación de la mandíbula, causando dolor en las articulaciones, dolores de cabeza o problemas de oído;
(xxiv)	Pueden ocurrir reacciones alérgicas; y Los dientes que no están al menos parcialmente cubiertos por el alineador pueden sufrir una supra erupción.
CONSENTIMIENTO INFORMADO
Me han dado tiempo suficiente para leer y he leído la información anterior que describe el tratamiento de ortodoncia con alineadores Wave®. Entiendo los beneficios, riesgos, alternativas e inconvenientes asociados con el tratamiento, así como la opción de no recibir tratamiento. Me han informado lo suficiente y he tenido la oportunidad de hacer preguntas y discutir inquietudes sobre el tratamiento de ortodoncia con productos Wave® con mi médico de quien tengo la intención de recibir tratamiento. Entiendo que solo debo usar los productos Wave® después de la consulta y prescripción de un médico capacitado en Wave®, y por la presente doy mi consentimiento para el tratamiento de ortodoncia con productos Wave® recetados por mi médico.
Debido al hecho de que la ortodoncia no concibe el error nulo, reconozco que mi médico y Wave® no tienen ni pueden ofrecer ninguna garantía o seguridad con respecto al resultado de mi tratamiento. Mi médico o Wave®, sus representantes, sucesores, cesionarios y agentes no me han hecho ninguna seguridad ni garantía de ningún tipo con respecto a ningún resultado específico de mi tratamiento.
Autorizo a mi médico a divulgar mis registros médicos, incluidos, entre otros, radiografías (rayos X), informes, gráficos, antecedentes médicos, fotografías, hallazgos, modelos de yeso o impresiones de dientes, recetas, diagnósticos, pruebas médicas, resultados de pruebas, facturación y otros registros de tratamiento en posesión de mi médico a otros dentistas u ortodoncistas con licencia y organizaciones que emplean dentistas y ortodoncistas con licencia y a Wave®, sus representantes, empleados, sucesores, cesionarios y agentes con el fin de investigar y revisar mi historial médico en lo que respecta a la ortodoncia tratamiento con productos de Wave® y con fines educativos y de investigación.
Entiendo que el uso de mis registros médicos puede resultar en la divulgación de mi "información de salud identificable individualmente" según lo define la Ley de portabilidad y responsabilidad del seguro médico ("HIPAA"). Por la presente doy mi consentimiento a la(s) divulgación(es) como se establece anteriormente. No buscaré, ni nadie en mi nombre buscará daños o remedios legales, equitativos o monetarios por dicha divulgación. Reconozco que el uso de mis registros médicos es sin compensación y que yo no tendré ni nadie en mi nombre tendrá `

export default bases;